# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryptly_backend', '0002_auto_20170309_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='private_key',
            field=models.CharField(max_length=8192),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='public_key',
            field=models.CharField(max_length=8192),
        ),
    ]
